//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", ConfigurationName="LmobileFieldWebservice_Port")]
public interface LmobileFieldWebservice_Port
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:CreateServiceOrder" +
        "s", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateServiceOrders_Result> CreateServiceOrdersAsync(CreateServiceOrders request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateDocAttachmen" +
        "t", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateDocAttachment_Result> UpdateDocAttachmentAsync(UpdateDocAttachment request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateExtensionFor" +
        "ServiceOrders", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateExtensionForServiceOrders_Result> UpdateExtensionForServiceOrdersAsync(UpdateExtensionForServiceOrders request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateServiceComme" +
        "ntLine", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateServiceCommentLine_Result> UpdateServiceCommentLineAsync(UpdateServiceCommentLine request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateServiceItemL" +
        "ine", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateServiceItemLine_Result> UpdateServiceItemLineAsync(UpdateServiceItemLine request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateServiceLine", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateServiceLine_Result> UpdateServiceLineAsync(UpdateServiceLine request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice:UpdateServiceOrder" +
        "s", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateServiceOrders_Result> UpdateServiceOrdersAsync(UpdateServiceOrders request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50075")]
public partial class ServiceOrderHeaderXML
{
    
    private ServiceOrderHeader[] serviceOrderHeaderField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceOrderHeader", Order=0)]
    public ServiceOrderHeader[] ServiceOrderHeader
    {
        get
        {
            return this.serviceOrderHeaderField;
        }
        set
        {
            this.serviceOrderHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50075")]
public partial class ServiceOrderHeader
{
    
    private string[] documentTypeField;
    
    private string[] noField;
    
    private string[] customerNoField;
    
    private string[] descriptionField;
    
    private string[] shiptoCodeField;
    
    private string[] salespersonCodeField;
    
    private string[] serviceOrderTypeField;
    
    private string[] strStartingDateField;
    
    private string[] strStartingTimeField;
    
    private string[] strFinishingDateField;
    
    private string[] strFinishingTimeField;
    
    private string[] statusField;
    
    private string[] kGM_MonteurField;
    
    private string[] lMNrField;
    
    private System.DateTime[] documentDateField;
    
    private string[] lMStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentType", Order=0)]
    public string[] DocumentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("No", Order=1)]
    public string[] No
    {
        get
        {
            return this.noField;
        }
        set
        {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerNo", Order=2)]
    public string[] CustomerNo
    {
        get
        {
            return this.customerNoField;
        }
        set
        {
            this.customerNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Order=3)]
    public string[] Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShiptoCode", Order=4)]
    public string[] ShiptoCode
    {
        get
        {
            return this.shiptoCodeField;
        }
        set
        {
            this.shiptoCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SalespersonCode", Order=5)]
    public string[] SalespersonCode
    {
        get
        {
            return this.salespersonCodeField;
        }
        set
        {
            this.salespersonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceOrderType", Order=6)]
    public string[] ServiceOrderType
    {
        get
        {
            return this.serviceOrderTypeField;
        }
        set
        {
            this.serviceOrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrStartingDate", Order=7)]
    public string[] StrStartingDate
    {
        get
        {
            return this.strStartingDateField;
        }
        set
        {
            this.strStartingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrStartingTime", Order=8)]
    public string[] StrStartingTime
    {
        get
        {
            return this.strStartingTimeField;
        }
        set
        {
            this.strStartingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrFinishingDate", Order=9)]
    public string[] StrFinishingDate
    {
        get
        {
            return this.strFinishingDateField;
        }
        set
        {
            this.strFinishingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrFinishingTime", Order=10)]
    public string[] StrFinishingTime
    {
        get
        {
            return this.strFinishingTimeField;
        }
        set
        {
            this.strFinishingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Status", Order=11)]
    public string[] Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KGM_Monteur", Order=12)]
    public string[] KGM_Monteur
    {
        get
        {
            return this.kGM_MonteurField;
        }
        set
        {
            this.kGM_MonteurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LMNr", Order=13)]
    public string[] LMNr
    {
        get
        {
            return this.lMNrField;
        }
        set
        {
            this.lMNrField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.DateTime[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0001-01-01' attribute on element name='DocumentDate'.
    [System.Xml.Serialization.XmlElementAttribute("DocumentDate", DataType="date", Order=14)]
    public System.DateTime[] DocumentDate
    {
        get
        {
            return this.documentDateField;
        }
        set
        {
            this.documentDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LMStatus", Order=15)]
    public string[] LMStatus
    {
        get
        {
            return this.lMStatusField;
        }
        set
        {
            this.lMStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50081")]
public partial class ServiceCommentLine
{
    
    private string[] strLineNoField;
    
    private string[] strCommentField;
    
    private string tableNameField;
    
    private string tableSubtypeField;
    
    private string noField;
    
    private string typeField;
    
    private string tableLineNoField;
    
    private string dateField;
    
    private string monteurField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrLineNo", Order=0)]
    public string[] StrLineNo
    {
        get
        {
            return this.strLineNoField;
        }
        set
        {
            this.strLineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrComment", Order=1)]
    public string[] StrComment
    {
        get
        {
            return this.strCommentField;
        }
        set
        {
            this.strCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TableName
    {
        get
        {
            return this.tableNameField;
        }
        set
        {
            this.tableNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TableSubtype
    {
        get
        {
            return this.tableSubtypeField;
        }
        set
        {
            this.tableSubtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string No
    {
        get
        {
            return this.noField;
        }
        set
        {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TableLineNo
    {
        get
        {
            return this.tableLineNoField;
        }
        set
        {
            this.tableLineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Monteur
    {
        get
        {
            return this.monteurField;
        }
        set
        {
            this.monteurField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50081")]
public partial class ServiceCommentLineXML
{
    
    private ServiceCommentLine[] serviceCommentLineField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceCommentLine", Order=0)]
    public ServiceCommentLine[] ServiceCommentLine
    {
        get
        {
            return this.serviceCommentLineField;
        }
        set
        {
            this.serviceCommentLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50080")]
public partial class extension
{
    
    private string[] tablenameField;
    
    private string[] tablekeyField;
    
    private string[] columnnameField;
    
    private string[] valueField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("table-name", Order=0)]
    public string[] tablename
    {
        get
        {
            return this.tablenameField;
        }
        set
        {
            this.tablenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("table-key", Order=1)]
    public string[] tablekey
    {
        get
        {
            return this.tablekeyField;
        }
        set
        {
            this.tablekeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("column-name", Order=2)]
    public string[] columnname
    {
        get
        {
            return this.columnnameField;
        }
        set
        {
            this.columnnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value", Order=3)]
    public string[] value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50080")]
public partial class ExtensionUpdateXML
{
    
    private extension[] extensionField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extension", Order=0)]
    public extension[] extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50077")]
public partial class Link
{
    
    private string[] linkURLField;
    
    private string[] descriptionField;
    
    private string[] idUserField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LinkURL", Order=0)]
    public string[] LinkURL
    {
        get
        {
            return this.linkURLField;
        }
        set
        {
            this.linkURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Order=1)]
    public string[] Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IdUser", Order=2)]
    public string[] IdUser
    {
        get
        {
            return this.idUserField;
        }
        set
        {
            this.idUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50077")]
public partial class Links
{
    
    private Link[] linkField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Link", Order=0)]
    public Link[] Link
    {
        get
        {
            return this.linkField;
        }
        set
        {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50077")]
public partial class AttacheFile
{
    
    private string[] tableNameField;
    
    private string[] documentTypeField;
    
    private string[] documentNoField;
    
    private Links[] linksField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tableName", Order=0)]
    public string[] tableName
    {
        get
        {
            return this.tableNameField;
        }
        set
        {
            this.tableNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("documentType", Order=1)]
    public string[] documentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("documentNo", Order=2)]
    public string[] documentNo
    {
        get
        {
            return this.documentNoField;
        }
        set
        {
            this.documentNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Links", Order=3)]
    public Links[] Links
    {
        get
        {
            return this.linksField;
        }
        set
        {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50077")]
public partial class AttacheObject
{
    
    private AttacheFile[] attacheFileField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AttacheFile", Order=0)]
    public AttacheFile[] AttacheFile
    {
        get
        {
            return this.attacheFileField;
        }
        set
        {
            this.attacheFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50079")]
public partial class ServiceLine
{
    
    private string[] customerNoField;
    
    private string[] documentTypeField;
    
    private string[] documentNoField;
    
    private string[] serviceItemNoField;
    
    private int[] serviceItemLineNoField;
    
    private int[] lineNoField;
    
    private string[] typeField;
    
    private string[] noField;
    
    private string[] locationCodeField;
    
    private string[] descriptionField;
    
    private string[] description2Field;
    
    private string[] workTypeCodeField;
    
    private string[] strPostingDateField;
    
    private string[] shiptoCodeField;
    
    private decimal[] unitCostLCYField;
    
    private decimal[] unitCostField;
    
    private string[] unitofMeasureCodeField;
    
    private decimal[] unitPriceField;
    
    private decimal[] quantityBField;
    
    private decimal[] quantityField;
    
    private decimal[] qtytoShipField;
    
    private decimal[] qtytoInvoiceField;
    
    private bool[] calculateField;
    
    private bool[] onReportField;
    
    private string[] eKStatusField;
    
    private string[] vendorNoField;
    
    private string[] shelfNoField;
    
    private string[] genBusPostingGroupField;
    
    private string[] vATProdPostingGroupField;
    
    private string[] shortcutDimensionCodeField;
    
    private string[] lineNoCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerNo", Order=0)]
    public string[] CustomerNo
    {
        get
        {
            return this.customerNoField;
        }
        set
        {
            this.customerNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentType", Order=1)]
    public string[] DocumentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentNo", Order=2)]
    public string[] DocumentNo
    {
        get
        {
            return this.documentNoField;
        }
        set
        {
            this.documentNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemNo", Order=3)]
    public string[] ServiceItemNo
    {
        get
        {
            return this.serviceItemNoField;
        }
        set
        {
            this.serviceItemNoField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='ServiceItemLineNo'.
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemLineNo", Order=4)]
    public int[] ServiceItemLineNo
    {
        get
        {
            return this.serviceItemLineNoField;
        }
        set
        {
            this.serviceItemLineNoField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='LineNo'.
    [System.Xml.Serialization.XmlElementAttribute("LineNo", Order=5)]
    public int[] LineNo
    {
        get
        {
            return this.lineNoField;
        }
        set
        {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Type", Order=6)]
    public string[] Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("No", Order=7)]
    public string[] No
    {
        get
        {
            return this.noField;
        }
        set
        {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationCode", Order=8)]
    public string[] LocationCode
    {
        get
        {
            return this.locationCodeField;
        }
        set
        {
            this.locationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Order=9)]
    public string[] Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description2", Order=10)]
    public string[] Description2
    {
        get
        {
            return this.description2Field;
        }
        set
        {
            this.description2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WorkTypeCode", Order=11)]
    public string[] WorkTypeCode
    {
        get
        {
            return this.workTypeCodeField;
        }
        set
        {
            this.workTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrPostingDate", Order=12)]
    public string[] StrPostingDate
    {
        get
        {
            return this.strPostingDateField;
        }
        set
        {
            this.strPostingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShiptoCode", Order=13)]
    public string[] ShiptoCode
    {
        get
        {
            return this.shiptoCodeField;
        }
        set
        {
            this.shiptoCodeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='UnitCostLCY'.
    [System.Xml.Serialization.XmlElementAttribute("UnitCostLCY", Order=14)]
    public decimal[] UnitCostLCY
    {
        get
        {
            return this.unitCostLCYField;
        }
        set
        {
            this.unitCostLCYField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='UnitCost'.
    [System.Xml.Serialization.XmlElementAttribute("UnitCost", Order=15)]
    public decimal[] UnitCost
    {
        get
        {
            return this.unitCostField;
        }
        set
        {
            this.unitCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UnitofMeasureCode", Order=16)]
    public string[] UnitofMeasureCode
    {
        get
        {
            return this.unitofMeasureCodeField;
        }
        set
        {
            this.unitofMeasureCodeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='UnitPrice'.
    [System.Xml.Serialization.XmlElementAttribute("UnitPrice", Order=17)]
    public decimal[] UnitPrice
    {
        get
        {
            return this.unitPriceField;
        }
        set
        {
            this.unitPriceField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='QuantityB'.
    [System.Xml.Serialization.XmlElementAttribute("QuantityB", Order=18)]
    public decimal[] QuantityB
    {
        get
        {
            return this.quantityBField;
        }
        set
        {
            this.quantityBField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='Quantity'.
    [System.Xml.Serialization.XmlElementAttribute("Quantity", Order=19)]
    public decimal[] Quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='QtytoShip'.
    [System.Xml.Serialization.XmlElementAttribute("QtytoShip", Order=20)]
    public decimal[] QtytoShip
    {
        get
        {
            return this.qtytoShipField;
        }
        set
        {
            this.qtytoShipField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='QtytoInvoice'.
    [System.Xml.Serialization.XmlElementAttribute("QtytoInvoice", Order=21)]
    public decimal[] QtytoInvoice
    {
        get
        {
            return this.qtytoInvoiceField;
        }
        set
        {
            this.qtytoInvoiceField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='Calculate'.
    [System.Xml.Serialization.XmlElementAttribute("Calculate", Order=22)]
    public bool[] Calculate
    {
        get
        {
            return this.calculateField;
        }
        set
        {
            this.calculateField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='OnReport'.
    [System.Xml.Serialization.XmlElementAttribute("OnReport", Order=23)]
    public bool[] OnReport
    {
        get
        {
            return this.onReportField;
        }
        set
        {
            this.onReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EKStatus", Order=24)]
    public string[] EKStatus
    {
        get
        {
            return this.eKStatusField;
        }
        set
        {
            this.eKStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VendorNo", Order=25)]
    public string[] VendorNo
    {
        get
        {
            return this.vendorNoField;
        }
        set
        {
            this.vendorNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShelfNo", Order=26)]
    public string[] ShelfNo
    {
        get
        {
            return this.shelfNoField;
        }
        set
        {
            this.shelfNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GenBusPostingGroup", Order=27)]
    public string[] GenBusPostingGroup
    {
        get
        {
            return this.genBusPostingGroupField;
        }
        set
        {
            this.genBusPostingGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VATProdPostingGroup", Order=28)]
    public string[] VATProdPostingGroup
    {
        get
        {
            return this.vATProdPostingGroupField;
        }
        set
        {
            this.vATProdPostingGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShortcutDimensionCode", Order=29)]
    public string[] ShortcutDimensionCode
    {
        get
        {
            return this.shortcutDimensionCodeField;
        }
        set
        {
            this.shortcutDimensionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LineNoCode", Order=30)]
    public string[] LineNoCode
    {
        get
        {
            return this.lineNoCodeField;
        }
        set
        {
            this.lineNoCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50079")]
public partial class ServiceLineXML
{
    
    private ServiceLine[] serviceLineField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceLine", Order=0)]
    public ServiceLine[] ServiceLine
    {
        get
        {
            return this.serviceLineField;
        }
        set
        {
            this.serviceLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50076")]
public partial class ServiceItemLine
{
    
    private string[] documentTypeField;
    
    private string[] documentNoField;
    
    private int[] lineNoField;
    
    private string[] serviceItemNoField;
    
    private string[] itemNoField;
    
    private decimal[] actualResponseTimeHoursField;
    
    private string[] adjustmentTypeField;
    
    private decimal[] baseAmounttoAdjustField;
    
    private int[] contractLineNoField;
    
    private string[] contractNoField;
    
    private string[] customerNoField;
    
    private string[] description2Field;
    
    private int[] dimensionSetIDField;
    
    private string[] faultAreaCodeField;
    
    private string[] faultCodeField;
    
    private bool[] faultCommentField;
    
    private string[] faultReasonCodeField;
    
    private string[] strFinishingDateField;
    
    private string[] strFinishingTimeField;
    
    private string[] loanerNoField;
    
    private string[] locationofServiceItemField;
    
    private int[] noofActiveFinishedAllocsField;
    
    private int[] noofAllocationsField;
    
    private int[] noofPreviousServicesField;
    
    private string[] releaseStatusField;
    
    private string[] repairStatusCodeField;
    
    private string[] resolutionCodeField;
    
    private bool[] resolutionCommentField;
    
    private string[] strResponseDateField;
    
    private decimal[] responseTimeHoursField;
    
    private string[] strResponseTimeField;
    
    private string[] responsibilityCenterField;
    
    private string[] serialNoField;
    
    private string[] servPriceAdjmtGrCodeField;
    
    private string[] serviceItemGroupCodeField;
    
    private bool[] serviceItemLoanerCommentField;
    
    private string[] serviceOrderFilterField;
    
    private string[] servicePriceGroupCodeField;
    
    private string[] serviceShelfNoField;
    
    private string[] shiptoCodeField;
    
    private string[] shortcutDimension1CodeField;
    
    private string[] shortcutDimension2CodeField;
    
    private string[] strStartingDateField;
    
    private string[] strStartingTimeField;
    
    private string[] symptomCodeField;
    
    private string[] variantCodeField;
    
    private string[] vendorItemNoField;
    
    private string[] vendorNoField;
    
    private decimal[] warrantyLaborField;
    
    private string[] descriptionField;
    
    private string[] priorityField;
    
    private bool[] warrantyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentType", Order=0)]
    public string[] DocumentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentNo", Order=1)]
    public string[] DocumentNo
    {
        get
        {
            return this.documentNoField;
        }
        set
        {
            this.documentNoField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='LineNo'.
    [System.Xml.Serialization.XmlElementAttribute("LineNo", Order=2)]
    public int[] LineNo
    {
        get
        {
            return this.lineNoField;
        }
        set
        {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemNo", Order=3)]
    public string[] ServiceItemNo
    {
        get
        {
            return this.serviceItemNoField;
        }
        set
        {
            this.serviceItemNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemNo", Order=4)]
    public string[] ItemNo
    {
        get
        {
            return this.itemNoField;
        }
        set
        {
            this.itemNoField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='ActualResponseTimeHours'.
    [System.Xml.Serialization.XmlElementAttribute("ActualResponseTimeHours", Order=5)]
    public decimal[] ActualResponseTimeHours
    {
        get
        {
            return this.actualResponseTimeHoursField;
        }
        set
        {
            this.actualResponseTimeHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdjustmentType", Order=6)]
    public string[] AdjustmentType
    {
        get
        {
            return this.adjustmentTypeField;
        }
        set
        {
            this.adjustmentTypeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='BaseAmounttoAdjust'.
    [System.Xml.Serialization.XmlElementAttribute("BaseAmounttoAdjust", Order=7)]
    public decimal[] BaseAmounttoAdjust
    {
        get
        {
            return this.baseAmounttoAdjustField;
        }
        set
        {
            this.baseAmounttoAdjustField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='ContractLineNo'.
    [System.Xml.Serialization.XmlElementAttribute("ContractLineNo", Order=8)]
    public int[] ContractLineNo
    {
        get
        {
            return this.contractLineNoField;
        }
        set
        {
            this.contractLineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContractNo", Order=9)]
    public string[] ContractNo
    {
        get
        {
            return this.contractNoField;
        }
        set
        {
            this.contractNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerNo", Order=10)]
    public string[] CustomerNo
    {
        get
        {
            return this.customerNoField;
        }
        set
        {
            this.customerNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description2", Order=11)]
    public string[] Description2
    {
        get
        {
            return this.description2Field;
        }
        set
        {
            this.description2Field = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='DimensionSetID'.
    [System.Xml.Serialization.XmlElementAttribute("DimensionSetID", Order=12)]
    public int[] DimensionSetID
    {
        get
        {
            return this.dimensionSetIDField;
        }
        set
        {
            this.dimensionSetIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FaultAreaCode", Order=13)]
    public string[] FaultAreaCode
    {
        get
        {
            return this.faultAreaCodeField;
        }
        set
        {
            this.faultAreaCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FaultCode", Order=14)]
    public string[] FaultCode
    {
        get
        {
            return this.faultCodeField;
        }
        set
        {
            this.faultCodeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='FaultComment'.
    [System.Xml.Serialization.XmlElementAttribute("FaultComment", Order=15)]
    public bool[] FaultComment
    {
        get
        {
            return this.faultCommentField;
        }
        set
        {
            this.faultCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FaultReasonCode", Order=16)]
    public string[] FaultReasonCode
    {
        get
        {
            return this.faultReasonCodeField;
        }
        set
        {
            this.faultReasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrFinishingDate", Order=17)]
    public string[] StrFinishingDate
    {
        get
        {
            return this.strFinishingDateField;
        }
        set
        {
            this.strFinishingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrFinishingTime", Order=18)]
    public string[] StrFinishingTime
    {
        get
        {
            return this.strFinishingTimeField;
        }
        set
        {
            this.strFinishingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LoanerNo", Order=19)]
    public string[] LoanerNo
    {
        get
        {
            return this.loanerNoField;
        }
        set
        {
            this.loanerNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationofServiceItem", Order=20)]
    public string[] LocationofServiceItem
    {
        get
        {
            return this.locationofServiceItemField;
        }
        set
        {
            this.locationofServiceItemField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='NoofActiveFinishedAllocs'.
    [System.Xml.Serialization.XmlElementAttribute("NoofActiveFinishedAllocs", Order=21)]
    public int[] NoofActiveFinishedAllocs
    {
        get
        {
            return this.noofActiveFinishedAllocsField;
        }
        set
        {
            this.noofActiveFinishedAllocsField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='NoofAllocations'.
    [System.Xml.Serialization.XmlElementAttribute("NoofAllocations", Order=22)]
    public int[] NoofAllocations
    {
        get
        {
            return this.noofAllocationsField;
        }
        set
        {
            this.noofAllocationsField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Int32[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='NoofPreviousServices'.
    [System.Xml.Serialization.XmlElementAttribute("NoofPreviousServices", Order=23)]
    public int[] NoofPreviousServices
    {
        get
        {
            return this.noofPreviousServicesField;
        }
        set
        {
            this.noofPreviousServicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReleaseStatus", Order=24)]
    public string[] ReleaseStatus
    {
        get
        {
            return this.releaseStatusField;
        }
        set
        {
            this.releaseStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RepairStatusCode", Order=25)]
    public string[] RepairStatusCode
    {
        get
        {
            return this.repairStatusCodeField;
        }
        set
        {
            this.repairStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResolutionCode", Order=26)]
    public string[] ResolutionCode
    {
        get
        {
            return this.resolutionCodeField;
        }
        set
        {
            this.resolutionCodeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='ResolutionComment'.
    [System.Xml.Serialization.XmlElementAttribute("ResolutionComment", Order=27)]
    public bool[] ResolutionComment
    {
        get
        {
            return this.resolutionCommentField;
        }
        set
        {
            this.resolutionCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrResponseDate", Order=28)]
    public string[] StrResponseDate
    {
        get
        {
            return this.strResponseDateField;
        }
        set
        {
            this.strResponseDateField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='ResponseTimeHours'.
    [System.Xml.Serialization.XmlElementAttribute("ResponseTimeHours", Order=29)]
    public decimal[] ResponseTimeHours
    {
        get
        {
            return this.responseTimeHoursField;
        }
        set
        {
            this.responseTimeHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrResponseTime", Order=30)]
    public string[] StrResponseTime
    {
        get
        {
            return this.strResponseTimeField;
        }
        set
        {
            this.strResponseTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResponsibilityCenter", Order=31)]
    public string[] ResponsibilityCenter
    {
        get
        {
            return this.responsibilityCenterField;
        }
        set
        {
            this.responsibilityCenterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SerialNo", Order=32)]
    public string[] SerialNo
    {
        get
        {
            return this.serialNoField;
        }
        set
        {
            this.serialNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServPriceAdjmtGrCode", Order=33)]
    public string[] ServPriceAdjmtGrCode
    {
        get
        {
            return this.servPriceAdjmtGrCodeField;
        }
        set
        {
            this.servPriceAdjmtGrCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemGroupCode", Order=34)]
    public string[] ServiceItemGroupCode
    {
        get
        {
            return this.serviceItemGroupCodeField;
        }
        set
        {
            this.serviceItemGroupCodeField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='ServiceItemLoanerComment'.
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemLoanerComment", Order=35)]
    public bool[] ServiceItemLoanerComment
    {
        get
        {
            return this.serviceItemLoanerCommentField;
        }
        set
        {
            this.serviceItemLoanerCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceOrderFilter", Order=36)]
    public string[] ServiceOrderFilter
    {
        get
        {
            return this.serviceOrderFilterField;
        }
        set
        {
            this.serviceOrderFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServicePriceGroupCode", Order=37)]
    public string[] ServicePriceGroupCode
    {
        get
        {
            return this.servicePriceGroupCodeField;
        }
        set
        {
            this.servicePriceGroupCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceShelfNo", Order=38)]
    public string[] ServiceShelfNo
    {
        get
        {
            return this.serviceShelfNoField;
        }
        set
        {
            this.serviceShelfNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShiptoCode", Order=39)]
    public string[] ShiptoCode
    {
        get
        {
            return this.shiptoCodeField;
        }
        set
        {
            this.shiptoCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShortcutDimension1Code", Order=40)]
    public string[] ShortcutDimension1Code
    {
        get
        {
            return this.shortcutDimension1CodeField;
        }
        set
        {
            this.shortcutDimension1CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShortcutDimension2Code", Order=41)]
    public string[] ShortcutDimension2Code
    {
        get
        {
            return this.shortcutDimension2CodeField;
        }
        set
        {
            this.shortcutDimension2CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrStartingDate", Order=42)]
    public string[] StrStartingDate
    {
        get
        {
            return this.strStartingDateField;
        }
        set
        {
            this.strStartingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StrStartingTime", Order=43)]
    public string[] StrStartingTime
    {
        get
        {
            return this.strStartingTimeField;
        }
        set
        {
            this.strStartingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SymptomCode", Order=44)]
    public string[] SymptomCode
    {
        get
        {
            return this.symptomCodeField;
        }
        set
        {
            this.symptomCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VariantCode", Order=45)]
    public string[] VariantCode
    {
        get
        {
            return this.variantCodeField;
        }
        set
        {
            this.variantCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VendorItemNo", Order=46)]
    public string[] VendorItemNo
    {
        get
        {
            return this.vendorItemNoField;
        }
        set
        {
            this.vendorItemNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VendorNo", Order=47)]
    public string[] VendorNo
    {
        get
        {
            return this.vendorNoField;
        }
        set
        {
            this.vendorNoField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Decimal[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='WarrantyLabor'.
    [System.Xml.Serialization.XmlElementAttribute("WarrantyLabor", Order=48)]
    public decimal[] WarrantyLabor
    {
        get
        {
            return this.warrantyLaborField;
        }
        set
        {
            this.warrantyLaborField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Order=49)]
    public string[] Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Priority", Order=50)]
    public string[] Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: DefaultValue attribute on members of type System.Boolean[] is not supported in this version of the .Net Framework.
    // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='false' attribute on element name='Warranty'.
    [System.Xml.Serialization.XmlElementAttribute("Warranty", Order=51)]
    public bool[] Warranty
    {
        get
        {
            return this.warrantyField;
        }
        set
        {
            this.warrantyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50076")]
public partial class ServiceItemLineXML
{
    
    private ServiceItemLine[] serviceItemLineField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceItemLine", Order=0)]
    public ServiceItemLine[] ServiceItemLine
    {
        get
        {
            return this.serviceItemLineField;
        }
        set
        {
            this.serviceItemLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateServiceOrders", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class CreateServiceOrders
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceOrderHeaderXML xmlServiceHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=1)]
    public ServiceItemLineXML xmlServicesItemLine;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=2)]
    public ServiceLineXML xmlServicesLine;
    
    public CreateServiceOrders()
    {
    }
    
    public CreateServiceOrders(ServiceOrderHeaderXML xmlServiceHeader, ServiceItemLineXML xmlServicesItemLine, ServiceLineXML xmlServicesLine)
    {
        this.xmlServiceHeader = xmlServiceHeader;
        this.xmlServicesItemLine = xmlServicesItemLine;
        this.xmlServicesLine = xmlServicesLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateServiceOrders_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class CreateServiceOrders_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public string return_value;
    
    public CreateServiceOrders_Result()
    {
    }
    
    public CreateServiceOrders_Result(string return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocAttachment", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateDocAttachment
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public AttacheObject xMLDocAttachment;
    
    public UpdateDocAttachment()
    {
    }
    
    public UpdateDocAttachment(AttacheObject xMLDocAttachment)
    {
        this.xMLDocAttachment = xMLDocAttachment;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocAttachment_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateDocAttachment_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public AttacheObject xMLDocAttachment;
    
    public UpdateDocAttachment_Result()
    {
    }
    
    public UpdateDocAttachment_Result(AttacheObject xMLDocAttachment)
    {
        this.xMLDocAttachment = xMLDocAttachment;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateExtensionForServiceOrders", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateExtensionForServiceOrders
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ExtensionUpdateXML xmlExtensionUpdate;
    
    public UpdateExtensionForServiceOrders()
    {
    }
    
    public UpdateExtensionForServiceOrders(ExtensionUpdateXML xmlExtensionUpdate)
    {
        this.xmlExtensionUpdate = xmlExtensionUpdate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateExtensionForServiceOrders_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateExtensionForServiceOrders_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public bool return_value;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=1)]
    public ExtensionUpdateXML xmlExtensionUpdate;
    
    public UpdateExtensionForServiceOrders_Result()
    {
    }
    
    public UpdateExtensionForServiceOrders_Result(bool return_value, ExtensionUpdateXML xmlExtensionUpdate)
    {
        this.return_value = return_value;
        this.xmlExtensionUpdate = xmlExtensionUpdate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceCommentLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceCommentLine
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceCommentLineXML xmlServiceCommentLine;
    
    public UpdateServiceCommentLine()
    {
    }
    
    public UpdateServiceCommentLine(ServiceCommentLineXML xmlServiceCommentLine)
    {
        this.xmlServiceCommentLine = xmlServiceCommentLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceCommentLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceCommentLine_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceCommentLineXML xmlServiceCommentLine;
    
    public UpdateServiceCommentLine_Result()
    {
    }
    
    public UpdateServiceCommentLine_Result(ServiceCommentLineXML xmlServiceCommentLine)
    {
        this.xmlServiceCommentLine = xmlServiceCommentLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceItemLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceItemLine
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceItemLineXML xmlServicesItemLine;
    
    public UpdateServiceItemLine()
    {
    }
    
    public UpdateServiceItemLine(ServiceItemLineXML xmlServicesItemLine)
    {
        this.xmlServicesItemLine = xmlServicesItemLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceItemLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceItemLine_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceItemLineXML xmlServicesItemLine;
    
    public UpdateServiceItemLine_Result()
    {
    }
    
    public UpdateServiceItemLine_Result(ServiceItemLineXML xmlServicesItemLine)
    {
        this.xmlServicesItemLine = xmlServicesItemLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceLine
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceLineXML xmlServicesLine;
    
    public UpdateServiceLine()
    {
    }
    
    public UpdateServiceLine(ServiceLineXML xmlServicesLine)
    {
        this.xmlServicesLine = xmlServicesLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceLine_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ServiceLineXML xmlServicesLine;
    
    public UpdateServiceLine_Result()
    {
    }
    
    public UpdateServiceLine_Result(ServiceLineXML xmlServicesLine)
    {
        this.xmlServicesLine = xmlServicesLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceOrders", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceOrders
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public ExtensionUpdateXML xmlExtensionUpdate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=1)]
    public ServiceItemLineXML xmlServicesItemLine;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=2)]
    public ServiceLineXML xmlServicesLine;
    
    public UpdateServiceOrders()
    {
    }
    
    public UpdateServiceOrders(ExtensionUpdateXML xmlExtensionUpdate, ServiceItemLineXML xmlServicesItemLine, ServiceLineXML xmlServicesLine)
    {
        this.xmlExtensionUpdate = xmlExtensionUpdate;
        this.xmlServicesItemLine = xmlServicesItemLine;
        this.xmlServicesLine = xmlServicesLine;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateServiceOrders_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", IsWrapped=true)]
public partial class UpdateServiceOrders_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LmobileFieldWebservice", Order=0)]
    public string return_value;
    
    public UpdateServiceOrders_Result()
    {
    }
    
    public UpdateServiceOrders_Result(string return_value)
    {
        this.return_value = return_value;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface LmobileFieldWebservice_PortChannel : LmobileFieldWebservice_Port, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class LmobileFieldWebservice_PortClient : System.ServiceModel.ClientBase<LmobileFieldWebservice_Port>, LmobileFieldWebservice_Port
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public LmobileFieldWebservice_PortClient() : 
            base(LmobileFieldWebservice_PortClient.GetDefaultBinding(), LmobileFieldWebservice_PortClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.LmobileFieldWebservice_Port.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LmobileFieldWebservice_PortClient(EndpointConfiguration endpointConfiguration) : 
            base(LmobileFieldWebservice_PortClient.GetBindingForEndpoint(endpointConfiguration), LmobileFieldWebservice_PortClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LmobileFieldWebservice_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(LmobileFieldWebservice_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LmobileFieldWebservice_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(LmobileFieldWebservice_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LmobileFieldWebservice_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateServiceOrders_Result> LmobileFieldWebservice_Port.CreateServiceOrdersAsync(CreateServiceOrders request)
    {
        return base.Channel.CreateServiceOrdersAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateServiceOrders_Result> CreateServiceOrdersAsync(ServiceOrderHeaderXML xmlServiceHeader, ServiceItemLineXML xmlServicesItemLine, ServiceLineXML xmlServicesLine)
    {
        CreateServiceOrders inValue = new CreateServiceOrders();
        inValue.xmlServiceHeader = xmlServiceHeader;
        inValue.xmlServicesItemLine = xmlServicesItemLine;
        inValue.xmlServicesLine = xmlServicesLine;
        return ((LmobileFieldWebservice_Port)(this)).CreateServiceOrdersAsync(inValue);
    }
    
    public System.Threading.Tasks.Task<UpdateDocAttachment_Result> UpdateDocAttachmentAsync(UpdateDocAttachment request)
    {
        return base.Channel.UpdateDocAttachmentAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateExtensionForServiceOrders_Result> UpdateExtensionForServiceOrdersAsync(UpdateExtensionForServiceOrders request)
    {
        return base.Channel.UpdateExtensionForServiceOrdersAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateServiceCommentLine_Result> UpdateServiceCommentLineAsync(UpdateServiceCommentLine request)
    {
        return base.Channel.UpdateServiceCommentLineAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateServiceItemLine_Result> UpdateServiceItemLineAsync(UpdateServiceItemLine request)
    {
        return base.Channel.UpdateServiceItemLineAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateServiceLine_Result> UpdateServiceLineAsync(UpdateServiceLine request)
    {
        return base.Channel.UpdateServiceLineAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<UpdateServiceOrders_Result> LmobileFieldWebservice_Port.UpdateServiceOrdersAsync(UpdateServiceOrders request)
    {
        return base.Channel.UpdateServiceOrdersAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateServiceOrders_Result> UpdateServiceOrdersAsync(ExtensionUpdateXML xmlExtensionUpdate, ServiceItemLineXML xmlServicesItemLine, ServiceLineXML xmlServicesLine)
    {
        UpdateServiceOrders inValue = new UpdateServiceOrders();
        inValue.xmlExtensionUpdate = xmlExtensionUpdate;
        inValue.xmlServicesItemLine = xmlServicesItemLine;
        inValue.xmlServicesLine = xmlServicesLine;
        return ((LmobileFieldWebservice_Port)(this)).UpdateServiceOrdersAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.LmobileFieldWebservice_Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.LmobileFieldWebservice_Port))
        {
            return new System.ServiceModel.EndpointAddress("http://v-bc.kgmnav.local:7047/Test/WS/Service-Test/Codeunit/LmobileFieldWebservic" +
                    "e");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return LmobileFieldWebservice_PortClient.GetBindingForEndpoint(EndpointConfiguration.LmobileFieldWebservice_Port);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return LmobileFieldWebservice_PortClient.GetEndpointAddress(EndpointConfiguration.LmobileFieldWebservice_Port);
    }
    
    public enum EndpointConfiguration
    {
        
        LmobileFieldWebservice_Port,
    }
}
