delete from crm.Task
delete from crm.LinkResource
delete from crm.FileResource
delete from crm.note
delete from sms.ServiceNotifications
delete from SMS.ServiceOrderTimePostings
delete from sms.ServiceOrderMaterial
delete from sms.ServiceOrderTimes
delete from sms.TimeEntry
delete from sms.ReplenishmentOrderItem
delete from sms.ReplenishmentOrder
delete from sms.ServiceOrderDispatch
delete from sms.ServiceContractInstallationRelationship
delete from sms.MaintenancePlan
delete from sms.ServiceContract
delete from sms.ServiceOrderHead
delete from sms.InstallationHead
delete from sms.ServiceObject
delete from sms.Expense
delete from crm.ArticleRelationship
delete from crm.Article
delete from crm.Company
delete from crm.Person
delete from crm.Communication
delete from crm.Project
delete from crm.[address]
delete from crm.[order]
delete from crm.contact
truncate table crm.UserRecentPages
truncate table crm.log
