SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('GetFutureUtcDate'))
DROP FUNCTION GetFutureUtcDate
GO

CREATE FUNCTION GetFutureUtcDate() RETURNS DATETIME
AS
BEGIN
	RETURN DATEADD(MINUTE, 5, GETUTCDATE())
END